apiVersion: v1
kind: Template
labels:
  template: rhdm7-full-ng
  xpaas: 1.4.0
message: An angular2 application for GPTE demo in the Decision Management Foundational course.
metadata:
  annotations:
    description: Application template for Red Hat GPTE Demos for DM7 integration.
    iconClass: icon-jboss
    openshift.io/display-name: Red Hat GPTE Angular2 Demo Application
    tags: rhdm,jboss,xpaas
    version: 1.0.0
  name: ng-gpte-demo.yaml
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The nodejs web server's http port for the angular application demo.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ng-dmf
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}-ng-dmf
- apiVersion: v1
  id: ${APPLICATION_NAME}-ng-dmf-http
  kind: Route
  metadata:
    annotations:
      description: Route for nodejs mortgages http service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ng-dmf
  spec:
    host: ${DECISION_CENTRAL_HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}-ng-dmf
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ng-dmf
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ng-dmf:latest
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/gpe-mw-training/gpte-ng-dmf.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'nodejs:latest'
          namespace: openshift
      type: Source
    triggers:
      - type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ng-dmf
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ConfigMap
  data:
    environment.prod.ts: >
      export const environment = {
        production: true,
        dmApiUrl: 'http://${APPLICATION_NAME}-kieserver-${PROJECT}.${CLUSTER}/',
        dmUserName: '${KIE_SERVER_USER}',
        dmCredentials: '${KIE_SERVER_PWD}',
      };

  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ng-environment
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ng-dmf
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}-ng-dmf
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-ng-dmf
        name: ${APPLICATION_NAME}-ng-dmf
      spec:
        containers:
        - image: ng-dmf:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 50
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: ${APPLICATION_NAME}-ng-dmf
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 50
            failureThreshold: 30
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 256Mi
          volumeMounts:
          - mountPath: /data
            name: environment-volume
            readOnly: true
        volumes:
        - configMap:
            name: ng-environment
          name: environment-volume
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-ng-dmf
        from:
          kind: ImageStreamTag
          name: ng-dmf:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: demo
  required: true
- displayName: KIE Admin User
  description: KIE administrator username
  name: KIE_ADMIN_USER
  value: adminUser
  required: false
- displayName: KIE Admin Password
  description: KIE administrator password
  name: KIE_ADMIN_PWD
  from: "[a-zA-Z]{6}[0-9]{1}!"
  generate: expression
  required: false
- displayName: Project name
  name: PROJECT
  value: dm-dtf
  required: true
- displayName: Cluster name
  name: CLUSTER
  value: apps.dev37.openshift.opentlc.com
  required: true
